export type Product = {
  slug: string;
  title: string;
  price: number;
  regularPrice?: number;
  currency: string;
  category: string;
  badge?: string;
  tagline: string;
  description: string;
  features: string[];
  turnaround: string;
  popular?: boolean;
};

export const products: Product[] = [
  {
    slug: "travel-ban-uae-check",
    title: "UAE Travel Ban Check",
    price: 2500,
    currency: "AED",
    category: "Immigration Checks",
    badge: "Most Popular",
    popular: true,
    tagline: "Know your travel status before it's too late.",
    description: "Comprehensive UAE travel ban verification through official channels. We check DNRD, ICA, and MOI databases to give you a definitive answer on your travel ban status in the UAE.",
    features: [
      "DNRD & ICA database check",
      "MOI records verification",
      "Official status certificate",
      "Human-verified results",
      "Confidential & secure",
    ],
    turnaround: "24–48 hours",
  },
  {
    slug: "labor-ban-check",
    title: "Labor Ban Check",
    price: 200,
    regularPrice: 200,
    currency: "AED",
    category: "Labour Ban Checks",
    tagline: "Verify your MOHRE labor ban status instantly.",
    description: "Wirestork offers a comprehensive Labour Ban Check Service designed to help individuals and businesses verify any active labor bans imposed by the UAE Ministry of Human Resources and Emiratisation (MOHRE).",
    features: [
      "MOHRE database verification",
      "Active ban status check",
      "Employer records search",
      "Compliance confirmation",
    ],
    turnaround: "Same day",
  },
  {
    slug: "online-lawyer-consultation",
    title: "Online Legal Consultation",
    price: 500,
    regularPrice: 500,
    currency: "AED",
    category: "Lawyer on Call",
    tagline: "Licensed lawyers. No appointments. No delays.",
    description: "Connect directly with licensed lawyers in Dubai and Saudi Arabia. Whether you're facing a travel ban, employment dispute, debt recovery, or a court summons, Wirestork streamlines the legal process with quick, confidential, and expert legal advice.",
    features: [
      "Licensed UAE & Saudi lawyers",
      "Video or phone consultation",
      "Employment & labor disputes",
      "Travel ban & immigration",
      "Debt recovery guidance",
      "Confidential sessions",
    ],
    turnaround: "Within 4 hours",
  },
  {
    slug: "client-credit-check",
    title: "Client Credit Check",
    price: 1499,
    regularPrice: 1499,
    currency: "AED",
    category: "Corporate Verifications",
    tagline: "Know who you're doing business with.",
    description: "Financial literacy and credit education are critical parts of the customer relationship. Our client credit check gives businesses a complete picture of a client's creditworthiness before entering into agreements.",
    features: [
      "Credit history analysis",
      "Al Etihad Credit Bureau data",
      "Payment behaviour report",
      "Risk scoring",
      "Business credit profile",
    ],
    turnaround: "2–3 business days",
  },
  {
    slug: "employee-check",
    title: "Employee Background Check",
    price: 550,
    regularPrice: 550,
    currency: "AED",
    category: "Corporate Verifications",
    tagline: "Hire with confidence. Screen with compliance.",
    description: "GDFRA-compliant employee background checks. Customize your screening packages with add-ons including criminal and sex offender checks.",
    features: [
      "Employment verification (5 years)",
      "Highest degree verification",
      "Criminal background check",
      "GDFRA compliance",
      "Reference verification",
    ],
    turnaround: "3–5 business days",
  },
  {
    slug: "uae-court-police-case-checking",
    title: "Court & Police Case Check",
    price: 1700,
    currency: "AED",
    category: "Police and Court Case Checks",
    badge: "All Emirates",
    tagline: "Full police and court records across all UAE emirates.",
    description: "Comprehensive court and police case check covering all seven UAE emirates. We search Dubai Courts, Abu Dhabi Judicial Department, Sharjah, and all other emirate records.",
    features: [
      "All 7 emirates covered",
      "Dubai Courts records",
      "Abu Dhabi Judicial Dept",
      "Police case records",
      "Criminal court search",
      "Official documentation",
    ],
    turnaround: "48–72 hours",
  },
  {
    slug: "debt-collection-agency",
    title: "Accounts Receivable Management",
    price: 1499,
    regularPrice: 1499,
    currency: "AED",
    category: "Corporate Verifications",
    tagline: "Slash overdue payments faster than any traditional agency.",
    description: "We are the modern debt collection agency in UAE. Hire us for your accounts receivable management and let us do the heavy lifting while you focus on your business.",
    features: [
      "Legal debt collection",
      "Negotiation & settlement",
      "Court filing support",
      "Payment plan management",
      "Monthly reporting",
    ],
    turnaround: "Ongoing engagement",
  },
  {
    slug: "legal-edge-personal",
    title: "Legal Edge | Personal Advisory Plan",
    price: 500,
    regularPrice: 500,
    currency: "AED",
    category: "Legal Plans",
    badge: "Subscription",
    tagline: "Personalized legal assistance for busy individuals.",
    description: "The Legal Edge plan is a family-friendly plan designed for expats working in the UAE. Available in three or six month subscriptions, the plan enables you to raise legal queries round the clock for unique legal matters.",
    features: [
      "Unlimited legal queries",
      "Round-the-clock support",
      "30% discount on all services",
      "Priority case handling",
      "Family coverage",
      "3 or 6 month plans",
    ],
    turnaround: "Immediate access",
  },
  {
    slug: "remove-travel-ban-in-uae",
    title: "Mercy Petition — Remove Travel Ban",
    price: 5500,
    regularPrice: 5500,
    currency: "AED",
    category: "Immigration Checks",
    tagline: "Apply for a DNRD Mercy Petition to remove your UAE travel ban.",
    description: "Apply now for a Mercy Petition to the DNRD to remove your travel ban in UAE. Required documents include a clear passport copy, digital passport photo with white background, and a brief reason for your visit.",
    features: [
      "DNRD petition filing",
      "Document preparation",
      "Case representation",
      "Status tracking",
      "Expert legal guidance",
    ],
    turnaround: "4–8 weeks",
  },
  {
    slug: "check-travel-ban-in-saudi-arabia",
    title: "Saudi Arabia Travel Ban Check",
    price: 2500,
    currency: "AED",
    category: "Immigration and Labor Check Saudi",
    tagline: "Official Saudi travel ban verification — fast and verified.",
    description: "Check your travel ban status in Saudi Arabia through official channels. Human-verified results from the Saudi Jawazat and MOI databases.",
    features: [
      "Jawazat database check",
      "Saudi MOI verification",
      "Human-verified results",
      "Official documentation",
      "Confidential process",
    ],
    turnaround: "24–72 hours",
  },
  {
    slug: "expess-service",
    title: "Express Service",
    price: 100,
    regularPrice: 100,
    currency: "AED",
    category: "Add-ons",
    tagline: "Priority processing for pre-purchased services.",
    description: "For pre-purchased services only. Get your results faster with our express processing. Applicable for all ban check services, excluding advanced Travel Ban and standard Saudi Checks.",
    features: [
      "Priority queue placement",
      "Faster turnaround",
      "Status notifications",
    ],
    turnaround: "Add-on only",
  },
  {
    slug: "legal-document-review",
    title: "Legal Document Review",
    price: 349,
    currency: "AED",
    category: "Document Review",
    tagline: "Expert contract & legal document reviews across the GCC.",
    description: "Upload your document securely and receive a thorough, expert review tailored to GCC legal standards. Fast, confidential, and reliable.",
    features: [
      "GCC-standard review",
      "Contract analysis",
      "Risk identification",
      "Revision recommendations",
      "24hr turnaround option",
    ],
    turnaround: "24–48 hours",
  },
  {
    slug: "uae-business-formation",
    title: "UAE Business Formation Consultation",
    price: 250,
    regularPrice: 500,
    currency: "AED",
    category: "Business Set up",
    badge: "50% off",
    tagline: "Start your UAE company with expert guidance.",
    description: "AED 500 — fully refundable when you choose Wirestork for your company setup. Get expert guidance on starting your UAE business. The UAE is ranked among the world's top destinations for business setup.",
    features: [
      "Free zone vs mainland advice",
      "License type guidance",
      "Cost estimation",
      "Document checklist",
      "Refundable on engagement",
    ],
    turnaround: "Same day consultation",
  },
  {
    slug: "saudi-jawazat-final-exit-paper",
    title: "Saudi Final Exit Paper",
    price: 200,
    regularPrice: 200,
    currency: "AED",
    category: "Saudi Services",
    tagline: "Official Saudi Jawazat final exit document retrieval.",
    description: "Official document retrieval for Saudi Jawazat Final Exit Paper. We handle the official process so you don't have to navigate the Saudi bureaucracy alone.",
    features: [
      "Official Jawazat retrieval",
      "Document authentication",
      "Status tracking",
      "Secure delivery",
    ],
    turnaround: "3–7 business days",
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}
